events {}
http {
    server {
        listen 80;

        location /api/ {
            root /var/www;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME /var/www/api/index.php;
            include fastcgi_params;
            fastcgi_param REQUEST_URI $request_uri;
        }

        location / {
            return 404;
        }
    }
}
